[package]
name = "rpfm_getset"
version = "2.2.1"
authors = ["Frodo45127 <frodo_gv@hotmail.com>"]
description = "Library to automate the creation of getters and setters in RPFM."
edition = "2018"

[lib]
proc-macro=true

[dependencies]
quote = "^1.0"
syn = "^1.0"
