name: Tests

on:
    push:
        branches: [ master, develop ]
    pull_request:
        branches: [ master, develop ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2

        - name: Build rpfm-lib.
          run: cargo build --verbose --lib
        - name: Build rpfm-cli.
          run: cargo build --verbose --bin rpfm_cli
        - name: Run tests.
          run: cargo test --verbose --lib
